sudo: required
services:
  - docker

before_install:
  - docker build -t prabu444/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run prabu444/react-test npm test -- --coverage

after_success:
  - docker build -t prabu444/multi-client ./client
  - docker build -t prabu444/multi-server ./server
  - docker build -t prabu444/multi-nginx ./nginx
  - docker build -t prabu444/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push prabu444/multi-client
  - docker push prabu444/multi-nginx
  - docker push prabu444/multi-server
  - docker push prabu444/multi-worker